import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve } from 'path'

/**
 * Vite plugin: Generate firebase-messaging-sw.js with env variables
 * Jadi API key tidak perlu di-hardcode di file public
 */
function firebaseSwPlugin() {
  return {
    name: 'generate-firebase-sw',

    configResolved(config) {
      const env = loadEnv(config.mode, config.root)

      const swContent = `/* eslint-disable no-undef */
/**
 * Firebase Cloud Messaging Service Worker
 * Auto-generated by Vite plugin — jangan edit manual
 */
importScripts('https://www.gstatic.com/firebasejs/11.8.0/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/11.8.0/firebase-messaging-compat.js')

firebase.initializeApp({
  apiKey: "${env.VITE_FIREBASE_API_KEY}",
  authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN}",
  projectId: "${env.VITE_FIREBASE_PROJECT_ID}",
  storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${env.VITE_FIREBASE_APP_ID}",
})

const messaging = firebase.messaging()

messaging.onBackgroundMessage((payload) => {
  console.log('[SW] Background message received:', payload)
  const notificationTitle = payload.notification?.title || 'SMIKOLE'
  const notificationOptions = {
    body: payload.notification?.body || 'Anda memiliki notifikasi baru',
    icon: '/logo.svg',
    badge: '/logo.svg',
    tag: payload.data?.notificationId || 'default',
    data: { url: '/notifikasi', ...payload.data }
  }
  self.registration.showNotification(notificationTitle, notificationOptions)
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = event.notification.data?.url || '/notifikasi'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url.includes(url) && 'focus' in client) return client.focus()
      }
      if (clients.openWindow) return clients.openWindow(url)
    })
  )
})
`
      // Write to public/ for dev server
      writeFileSync(resolve(config.root, 'public/firebase-messaging-sw.js'), swContent)
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    firebaseSwPlugin(),
  ],
})
